export const {
  BASE_URL,
  VITE_TXTAI_URL,
  VITE_PGVECTOR_URL,
  VITE_OPENAI_API_KEY,
  VITE_FIREBASE_AUTH_CONFIG_API_KEY,
  VITE_FIREBASE_AUTH_CONFIG_AUTH_DOMAIN,
  VITE_FIREBASE_AUTH_CONFIG_PROJECT_ID,
  VITE_FIREBASE_AUTH_CONFIG_STORAGE_BUCKET,
  VITE_FIREBASE_AUTH_CONFIG_MESSAGING_SENDER_ID,
  VITE_FIREBASE_AUTH_CONFIG_APP_ID,
  VITE_FIREBASE_AUTH_CONFIG_MEASUREMENT_ID,
} = import.meta.env;
